### ISSUE TITLE
Need to define behavior of media.remote when disableRemotePlayback = true

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#47] opened 2016-06-30 23:04 UTC
The spec currently reads,

> If the disableRemotePlayback attribute is present on the media element, the user agent must not play the media remotely or present any UI to do so.

But the media element must still return an instance of RemotePlayback.  The behavior of this object should be defined when disableRemotePlayback is present.

**Comment by avayvod** [comment] 2016-07-05 20:42
I think this is a duplicate of Issue #6

**Closed as completed by avayvod** 2016-07-05 20:42 UTC
